version: '3'

services:

  app:
    image: "probotsocial/app:latest"
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true

  livy:
    container_name: livy
    image: "probotsocial/livy:latest"
    ports:
      - 8998:8998
      - 8999:4040
    volumes:
      - "$WORKDIR:/workdir"
      - "$WORKDIR/dist/probot-jar-with-dependencies.jar:/src/livy/apache-livy-0.7.0-incubating-bin/repl_2.11-jars/probot-jar-with-dependencies.jar"
      - "$WORKDIR/dist/probot-jar-with-dependencies.jar:/jars/probot-jar-with-dependencies.jar"
    links:
      - "postgres:postgres"

  microservice:
    container_name: microservice
    image: "probotsocial/microservice:latest"
    ports:
      - 10000:10000
    links:
      - "postgrest:postgrest"
    volumes:
      - "$WORKDIR:/workdir"
      - "$WORKDIR/microservice.conf:/application.conf"

  ngrok:
    image: "wernight/ngrok:latest"
    ports:
      - 4040:4040
      - 8080:8080
    links:
      - "microservice:microservice"
    environment:
      - NGROK_AUTH
      - NGROK_SUBDOMAIN
      - NGROK_PORT=microservice:10000

  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - "$WORKDIR/volumes/postgres:/var/lib/postgresql/data"

  postgrest:
    image: "postgrest/postgrest:latest"
    ports:
      - 5000:3000
    links:
      - "postgres:postgres"
    volumes:
      - "$WORKDIR/postgrest.conf:/etc/postgrest.conf"
