version: '3'

services:

  app:
    image: "probot/app:latest"
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:80
    environment:
      - CHOKIDAR_USEPOLLING=true

  livy:
    container_name: livy
    image: "probot/apache-livy:latest"
    ports:
      - 8998:8998
    volumes:
      - "$WORKDIR:/workdir"
      - "$WORKDIR/dist:/jars"
    links:
      - "postgres:postgres"

  microservice:
    container_name: microservice
    image: "probot/microservice:latest"
    ports:
      - 10000:10000
    volumes:
      - "$WORKDIR:/workdir"
      - "$WORKDIR/microservice.conf:/application.conf"

  ngrok:
    image: "wernight/ngrok:latest"
    ports:
      - 8080:8080
    links:
      - "microservice:microservice"
    environment:
      - NGROK_SUBDOMAIN=64402502886e
      - NGROK_PORT=microservice:10000

  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - "$WORKDIR/volumes/postgres:/var/lib/postgresql/data"

  postgrest:
    image: "postgrest/postgrest:latest"
    ports:
      - 5000:5000
    links:
      - "postgres:postgres"
    volumes:
      - "$WORKDIR/postgrest.conf:/etc/postgrest.conf"
